version: "3.8"

x-common-env: &common-env
  PUID: "100"
  PGID: "100"
  TZ: "America/Kentucky/Louisville"
  UMASK_SET: "002"

networks:
  media-net:
    name: media-net
    external: true   # create once with: docker network create media-net

volumes:
  media_dir:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/media }
  jellyfin_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/jellyfin/config }
  jellyfin_cache:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/jellyfin/cache }
  jellyseerr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/jellyseerr/config }
  radarr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/radarr }
  sonarr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/sonarr }
  prowlarr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/prowlarr }
  qb_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/qbittorrent/ }

services:
  # ----------------------------------------------------------
  # VPN gateway for qBittorrent (Mullvad + WireGuard)
  # ----------------------------------------------------------
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add: [ NET_ADMIN ]
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # --- Mullvad WireGuard ---
      - VPN_SERVICE_PROVIDER=mullvad        # alias VPNSP also works
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=10.70.95.99/32     # e.g. 10.x.y.z/32 from Mullvad config
      - WIREGUARD_PRIVATE_KEY=r8cd5CZuDYoBfFCpLgdg87OcE0N71wcjATTnzrRWo1A=
      # — stabilize the tunnel —
      #- WIREGUARD_ENDPOINT_PORT=53           # try 53, else 443
      - WIREGUARD_MTU=1320                   # try 1360 → 1320 if needed
      # If kernel WG keeps failing on your platform, try:
      - WIREGUARD_IMPLEMENTATION=userspace  # forces boringtun

      # — DNS for this gluetun version (rename var) —
      - DOT=off
      - DNS_ADDRESS=10.64.0.1                # Mullvad WG DNS
      # (remove any DNS_PLAINTEXT_ADDRESS / DNS_KEEP_NAMESERVER lines)

      # — stop brittle public IP probing —
      - PUBLICIP_ENABLED=off
      - PUBLICIP_PERIOD=0

      # — healthcheck tweak (optional) —
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443

      # — firewall / WebUI passthrough —
      - FIREWALL=on
      - FIREWALL_INPUT_PORTS=8080
      - TZ="America/Kentucky/Louisville"

    volumes:
      - /lib/modules:/lib/modules:ro
      - qb_config:/gluetun
    # Publish ONLY the WebUI; all other qBittorrent traffic egresses via VPN
    ports:
      - "8080:8080/tcp"                     # qBittorrent WebUI through gluetun
    networks: [ media-net ]
    restart: unless-stopped

  # ----------------------------------------------------------
  # qBittorrent (all traffic bound to gluetun)
  # ----------------------------------------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # Bind to gluetun's network namespace so traffic is forced through the VPN
    network_mode: service:gluetun
    depends_on: [ gluetun ]
    environment:
      PUID: "100"
      PGID: "100"
      TZ: "America/Kentucky/Louisville"
      UMASK: "002"     # LSIO uses UMASK; we map your UMASK_SET here
      WEBUI_PORT: "8080"
    volumes:
      - qb_config:/config
      - media_dir:/downloads
    restart: unless-stopped

  # ----------------------------------------------------------
  # Prowlarr
  # (Optionally route via gluetun's HTTP proxy by setting HTTP(S)_PROXY below)
  # ----------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      <<: *common-env
      # Optional: send only indexer egress via gluetun proxy (if enabled there)
      # HTTP_PROXY:  http://gluetun:8888
      # HTTPS_PROXY: http://gluetun:8888
      # NO_PROXY:    localhost,127.0.0.1,radarr,sonarr,jellyfin,jellyseerr
    volumes:
      - prowlarr_config:/config
      - media_dir:/data
    networks: [ media-net ]
    ports:
      - "9696:9696"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Radarr
  # ----------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment: *common-env
    volumes:
      - radarr_config:/config
      - media_dir:/data
    networks: [ media-net ]
    ports:
      - "7878:7878"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Sonarr
  # ----------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment: *common-env
    volumes:
      - sonarr_config:/config
      - media_dir:/data
    networks: [ media-net ]
    ports:
      - "8989:8989"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Jellyseerr
  # ----------------------------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ="America/Kentucky/Louisville"
    volumes:
      - jellyseerr_config:/app/config
    networks: [ media-net ]
    ports:
      - "5055:5055"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Jellyfin (with VA-API devices)
  # ----------------------------------------------------------
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    environment:
      - TZ="America/Kentucky/Louisville"
      - JELLYFIN_PublishedServerUrl=jellyfin.nacho
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - media_dir:/media
      - /dev/dri:/dev/dri
    networks: [ media-net ]
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "8920:8920"
    restart: unless-stopped
