version: "3.8"

networks:
  media-net:
    name: media-net
    external: true   # create once with: docker network create media-net

volumes:
  media_dir:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/media }
  jellyfin_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/jellyfin/config }
  jellyfin_cache:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/jellyfin/cache }
  jellyseerr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/jellyseerr/config }
  radarr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/radarr }
  sonarr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/sonarr }
  prowlarr_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/prowlarr }
  qb_config:
    driver: local
    driver_opts: { type: none, o: bind, device: /mnt/docker/qbittorrent/ }

services:
  # ----------------------------------------------------------
  # VPN gateway for qBittorrent (Proton + OpenVPN)
  # ----------------------------------------------------------
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add: [ NET_ADMIN ]
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - stack.env
    environment:
      # --- ProtonVPN OpenVPN Configuration ---
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      # OPENVPN_USER and OPENVPN_PASSWORD are loaded from stack.env
      - PORT_FORWARD_ONLY=off
      - FIREWALL_VPN_INPUT_PORTS=53131
      - VPN_PORT_FORWARDING=on
      - SERVER_HOSTINGS=node-be-75.protonvpn.net
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    volumes:
      - /lib/modules:/lib/modules:ro
      - qb_config:/gluetun
    # Publish ONLY the WebUI; all other qBittorrent traffic egresses via VPN
    ports:
      - "8080:8080/tcp"                     # qBittorrent WebUI through gluetun
    networks: [ media-net ]
    restart: unless-stopped

  # ----------------------------------------------------------
  # qBittorrent (all traffic bound to gluetun)
  # ----------------------------------------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # Bind to gluetun's network namespace so traffic is forced through the VPN
    network_mode: service:gluetun
    depends_on: [ gluetun ]
    env_file:
      - stack.env
    environment:
      UMASK: "002"     # LSIO uses UMASK instead of UMASK_SET
      WEBUI_PORT: "8080"
    volumes:
      - qb_config:/config
      - media_dir:/data
    restart: unless-stopped

  # ----------------------------------------------------------
  # Prowlarr
  # (Optionally route via gluetun's HTTP proxy by setting HTTP(S)_PROXY below)
  # ----------------------------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - stack.env
    # Optional proxy settings (uncomment if needed):
    # environment:
    #   HTTP_PROXY:  http://gluetun:8888
    #   HTTPS_PROXY: http://gluetun:8888
    #   NO_PROXY:    localhost,127.0.0.1,radarr,sonarr,jellyfin,jellyseerr
    volumes:
      - prowlarr_config:/config
      - media_dir:/data
    networks: [ media-net ]
    ports:
      - "9696:9696"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Radarr
  # ----------------------------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - stack.env
    volumes:
      - radarr_config:/config
      - media_dir:/data
    networks: [ media-net ]
    ports:
      - "7878:7878"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Sonarr
  # ----------------------------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - stack.env
    volumes:
      - sonarr_config:/config
      - media_dir:/data
    networks: [ media-net ]
    ports:
      - "8989:8989"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Jellyseerr
  # ----------------------------------------------------------
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - stack.env
    environment:
      - LOG_LEVEL=info
    user: "1000:1000"
    volumes:
      - /mnt/docker/jellyseerr/config:/app/config
    networks: [ media-net ]
    ports:
      - "5055:5055"
    restart: unless-stopped

  # ----------------------------------------------------------
  # Jellyfin (with VA-API devices)
  # ----------------------------------------------------------
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    group_add:
      - 44
      - 993
    env_file:
      - stack.env
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - media_dir:/media
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    networks: [ media-net ]
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "8920:8920"
    restart: unless-stopped
