services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add: [ NET_ADMIN ]
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # --- Mullvad + WireGuard ---
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}   # from Mullvad config generator
      - WIREGUARD_ADDRESS=${WG_ADDRESS}           # e.g. 10.x.y.z/32 from the same config
      # Optionally pick an exit location (one of):
      - SERVER_COUNTRIES=Canada
      # - SERVER_CITIES=Chicago
      # --- Firewall / access ---
      - FIREWALL=on
      - FIREWALL_INPUT_PORTS=8080                 # allow LAN to reach WebUI on host:8080
      # No VPN input ports: Mullvad no longer supports port-forwarding.
      # - FIREWALL_VPN_INPUT_PORTS=
      # Optional: built-in HTTP proxy for *Arr/Prowlarr* via VPN
      # - HTTPPROXY=on
      # - HTTPPROXY_LISTENING_ADDRESS=:8888
      - TZ=${TZ}
    volumes:
      - /lib/modules:/lib/modules:ro
      - qb_config:/gluetun
    ports:
      - "8080:8080/tcp"                           # qBittorrent WebUI via gluetun
      # NOTE: Do NOT publish torrent peer ports with Mullvad (no PF support).
    networks: [ media-net ]
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"               # all traffic via VPN namespace
    depends_on: [ gluetun ]
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      UMASK_SET: "${UMASK_SET}"
      WEBUI_PORT: "8080"
      # Optional: set a fixed listening port even without PF
      # TORRENTING_PORT: "6881"
    volumes:
      - qb_config:/config
      - media_dir:/downloads
    restart: unless-stopped
